name: '华为 应用商店上传 app Action'
description: '华为 应用商店上传 app Action 华为 接口具体查看文档 https://developer.huawei.com/consumer/cn/doc/AppGallery-connect-References/agcapi-app-info-query-0000001158365045'
author: 'weihongbin1 <1602586227@qq.com>'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  client_id:
    description: 'client_id'
    required: true
  client_secret:
    description: 'client_secret'
    required: true
  app_id:
    description: '应用id'
    required: true
  apk_file_path:
    description: 'apk 文件路径'
    required: true
  update_desc:
    description: '更新描述'
    required: true
  online_time:
    description: '上线时间'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'